name = "backend"
compatibility_date = "2024-08-08"
main = "src/index.ts"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "micro-todo-db"
# database_id = "72232f39-1d64-496a-95f0-4b0bf0fbf09c"

# [ai]
# binding = "AI"