/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UserIndexImport } from './routes/user.index'
import { Route as UserNosukeImport } from './routes/user.$nosuke'
import { Route as UserTestNosukeImport } from './routes/user.test.nosuke'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserIndexRoute = UserIndexImport.update({
  path: '/user/',
  getParentRoute: () => rootRoute,
} as any)

const UserNosukeRoute = UserNosukeImport.update({
  path: '/user/$nosuke',
  getParentRoute: () => rootRoute,
} as any)

const UserTestNosukeRoute = UserTestNosukeImport.update({
  path: '/user/test/nosuke',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/user/$nosuke': {
      id: '/user/$nosuke'
      path: '/user/$nosuke'
      fullPath: '/user/$nosuke'
      preLoaderRoute: typeof UserNosukeImport
      parentRoute: typeof rootRoute
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserIndexImport
      parentRoute: typeof rootRoute
    }
    '/user/test/nosuke': {
      id: '/user/test/nosuke'
      path: '/user/test/nosuke'
      fullPath: '/user/test/nosuke'
      preLoaderRoute: typeof UserTestNosukeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  UserNosukeRoute,
  UserIndexRoute,
  UserTestNosukeRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/user/$nosuke",
        "/user/",
        "/user/test/nosuke"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/user/$nosuke": {
      "filePath": "user.$nosuke.tsx"
    },
    "/user/": {
      "filePath": "user.index.tsx"
    },
    "/user/test/nosuke": {
      "filePath": "user.test.nosuke.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
